### ISSUE TITLE
wrong pianoman on repo?

### ISSUE THREAD

**Issue by pianoman19372** [harley-wewax/love2dGame#1]
hi there!

Did you mean to add me as a contributor to your project? 
I'm not sure i know who you are, or what your project is about

**Comment by harley-wewax** [comment]
Yes I apologize you and my friend have very similar names!

Just so you know, I'm creating the framework for a 2d Game engine written in Lua on top of the Love2D library.

**Comment by pianoman19372** [comment]
haha, i figured you meant someone else when i saw your timeline.    cool project.   good luck with that
